name: 'Pull Request another repository'
description: 'Used for pull request a copy of a folder to another repository'
inputs:
  title:
    description: 'PR Title'
    required: false
  comment:
    description: 'PR Comment'
    required: false
  source_folders:
    description: 'Source folder from origin'
    required: true
  destination_repo:
    description: 'Destination repository'
    required: true
  destination_folders:
    description: 'Destination folder to push the origin folder'
    required: false
  user_email:
    description: 'Email for the git commit'
    required: true
  user_name:
    description: 'GitHub username for the commit'
    required: true
  destination_head_branch:
    description: 'The branch to create to push the changes. Cannot be master or main'
    required: true
  destination_base_branch:
    description: 'The branch into which you want your code merged.'
    required: false
    default: "main"
  pull_request_reviewers:
    description: 'Pull request reviewers users'
    required: false
  labels:
    description: 'Labels to be added to the PR'
    required: false

outputs:
  pr_number: # number of created pr
    value: ${{steps.create-pr.outputs.PR_NUMBER}}
    description: 'PR number'

runs:
  using: 'composite'
  steps:
    - name: Run entrypoint script
      id: create-pr
      shell: bash
      run: bash ${{ github.action_path }}/entrypoint.sh
      env:
        INPUT_SOURCE_FOLDERS: ${{ inputs.source_folders }}
        INPUT_DESTINATION_FOLDERS: ${{ inputs.destination_folders }}
        INPUT_DESTINATION_REPO: ${{ inputs.destination_repo }}
        INPUT_TITLE: ${{ inputs.title }}
        INPUT_COMMENT: ${{ inputs.comment }}
        INPUT_USER_EMAIL: ${{ inputs.user_email }}
        INPUT_USER_NAME: ${{ inputs.user_name }}
        INPUT_DESTINATION_HEAD_BRANCH: ${{ inputs.destination_head_branch }}
        INPUT_DESTINATION_BASE_BRANCH: ${{ inputs.destination_base_branch }}
        INPUT_PULL_REQUEST_REVIEWERS: ${{ inputs.pull_request_reviewers }}
        INPUT_LABELS: ${{ inputs.labels }}
branding:
  icon: 'git-commit'
  color: 'green'